version: "3.8"

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    restart: always
    ports:
      - "9042:9042"
    volumes:
      - "cassandra_data:/var/lib/cassandra"
    networks:
      - brokerNet
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - "mongodb_data:/data/db"
    networks:
      - brokerNet
networks:
  brokerNet:
    name: brokerNet
    driver: bridge
    attachable: true
volumes:
  cassandra_data:
    driver: local
  mongodb_data:
    driver: local