version: "3.8"

services:
  cassandra:
#    image: cassandra:latest
    build: .
    container_name: cassandra
    restart: always
    ports:
      - "9042:9042"
    volumes:
      - "cassandra_data:/var/lib/cassandra"
    healthcheck:
      test: ["CMD",""]
    networks:
      - brokerNet
networks:
  brokerNet:
    name: brokerNet
    driver: bridge
    attachable: true
volumes:
  cassandra_data:
    driver: local