server:
  port: 5001
spring:
  data:
    cassandra:
      contact-points: localhost:9042
      local-datacenter: datacenter1

      keyspace-name: broker_account
  kafka:
    listener:
      ack-mode: manual_immediate
    consumer:
      bootstrap-servers: localhost:9092
      group-id: brokerAccountConsumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'


